Module 7 - Auth all tasks
js-tasks-ru/nodejs-20221117_tokes52 pull request #7
Opened 2023-01-02 21:54 UTC by stnnjs

2023-01-02 21:55 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2023-01-03 13:13 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2023-01-04 16:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2023-01-04 20:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2023-01-04 20:26 UTC, stnnjs commented
@tadjik1 
я слил все таски с 6 по 9 модуля в один PR, чтобы не ждать поочередного завершения очереди PR для прохождения тестов, он все равно уже 2 недели висел с 6 модулем :)

2023-01-25 09:06 UTC, tadjik1 commented on 06-mongodb-mongoose/02-rest-api/controllers/products.js
> +    return next();
обычно если вы уже сформировали ответ пользователю (в данном случае ошибку) - то не имеет смысл передавать управление дальше, т.к. запрос обработан.

2023-01-25 09:07 UTC, tadjik1 commented on 07-authentication/02-oauth/config.js
> +      app_secret: process.env.GITHUB_APP_SECRET || '6967b9e7f583f56728bff81513b525a7d770ecef',
удалите, пожалуйста, из гитхаба @stnnjs

2023-01-25 09:07 UTC, tadjik1 commented on 07-authentication/03-sessions/config.js
> +      app_secret: process.env.GITHUB_APP_SECRET || '6967b9e7f583f56728bff81513b525a7d770ecef',
и это тоже

2023-01-25 09:08 UTC, tadjik1 requested changes
@stnnjs  все выполнено отлично! я оставил лишь один комментарий по коду. 
пожалуйста, удалите секретные ключи, они не должны быть в репозитории, это небезопасно

2023-02-01 14:55 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2023-02-02 08:50 UTC, tadjik1 commented on 06-mongodb-mongoose/02-rest-api/controllers/products.js
> +    return;
👍

2023-02-02 08:50 UTC, tadjik1 approved these changes
все отлично! 🥇

2023-02-02 08:56 UTC, merged